spring:
  application:
    name: service-provider
  autoconfigure:
    exclude: org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistrationAutoConfiguration
  cloud:
    gateway:
      routes:
      - id: rest
        uri: http://127.0.0.1:8909/hello # 被代理的 URI
        predicates:
        - Path=/rest/hello
        filters:
        - StripPrefix=1
